name: Telegram Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install -r yuklama.txt
    
    - name: Run bot
      env:
       API: 8697498372:AAFlPPHvJzdBzu1xqzoxPqZk_CV-Q5k3FoI
      run: |
        python main.py
